Add initial code

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -1,18 +1,20 @@
 # Update bump details accordingly. Use bump check to confirm.
-# bump: lazygit-version /LAZYGIT_VERSION="(.*)"/ https://github.com/jesseduffield/lazygit.git|semver:*
-# LAZYGIT_VERSION="V.R.M" # Specify a stable release
-# export ZOPEN_STABLE_TAG="v${LAZYGIT_VERSION}"
-export ZOPEN_STABLE_URL="https://github.com/jesseduffield/lazygit.git"
-export ZOPEN_STABLE_DEPS="comp_go wharf"
+# bump: gitlfs-version /GITLFS_VERSION="(.*)"/ https://github.com/git-lfs/git-lfs|semver:*
+GITLFS_VERSION="3.4.1"
+export ZOPEN_STABLE_TAG="v${GITLFS_VERSION}"
+export ZOPEN_STABLE_URL="https://github.com/git-lfs/git-lfs.git"
+export ZOPEN_STABLE_DEPS="comp_go wharf tar gzip"
 export ZOPEN_BUILD_LINE="STABLE"
 export ZOPEN_CATEGORIES="devops utilities editor"
+
+export ZOPEN_TARBALL_MAN_URL="https://github.com/git-lfs/git-lfs/releases/download/v${GITLFS_VERSION}/git-lfs-linux-s390x-v${GITLFS_VERSION}.tar.gz"
 
 export ZOPEN_COMP=GO
 export ZOPEN_CONFIGURE="zopen_wharf"
 export ZOPEN_CONFIGURE_MINIMAL=1
 export ZOPEN_MAKE="zopen_build"
 export ZOPEN_MAKE_MINIMAL=1
-export ZOPEN_CHECK="skip"
+export ZOPEN_CHECK="zopen_check"
 export ZOPEN_CLEAN="zopen_clean"
 export ZOPEN_INSTALL="zopen_install"
 export ZOPEN_COMP=GO
@@ -26,38 +28,22 @@ zopen_init()
 
 zopen_build()
 {
-  echo $PWD
-  go version
   go build
+}
+
+zopen_check()
+{
+  go test -count=1
 }
 
 zopen_wharf()
 {
-  PTY_TAG="v1.1.21"
   cd .. && echo ""
-  git clone https://github.com/creack/pty.git
-  echo "Checking out $PTY_TAG"
-  cd pty && git -c advice.detachedHead=false checkout $PTY_TAG
-  curl -s -o pty--$PTY_TAG.patch "https://raw.githubusercontent.com/ZOSOpenTools/wharf/main/deps-patches/pty--$PTY_TAG.patch"
-  git apply -v pty--$PTY_TAG.patch
-  cd ..
-
-  git clone https://github.com/atotto/clipboard.git
-  git clone https://github.com/OpenPeeDeeP/xdg.git
-  cd xdg; git apply ../patches/xdg.gopatch; cd ..
-  git clone https://github.com/sirupsen/logrus.git
-  git clone https://github.com/spf13/afero.git
-  git clone https://github.com/jesseduffield/gocui.git
-  cd gocui; git apply ../patches/gui_others.gopatch; cd ..
-  git clone https://github.com/jesseduffield/go-git.git
-  cd go-git; git apply ../patches/go-git.gopatch; cd ..
+  git clone https://github.com/olekukonko/ts.git
   
-  go work init ./lazygit ./clipboard ./xdg ./logrus ./afero ./gocui ./go-git ./pty
-  wharf ./lazygit/...
-  wharf ./clipboard/...
-  wharf ./logrus/...
-  wharf ./afero/...
-  cd ./lazygit
+  go work init ./git-lfs ./ts
+  wharf ./git-lfs/...
+  cd ./git-lfs
 }
 
 zopen_clean()
@@ -70,7 +56,48 @@ zopen_install()
   go install 
 }
 
+zopen_post_install()
+{
+  # Install man pages from ${GIT_MANPAGES_URL}
+  GIT_SRC_DIR="${PWD}"
+  GIT_ROOT="${GIT_SRC_DIR}/.."
+  GIT_MAN_REL_DIR="gitlfs-manpages"
+  GIT_MAN_DIR="${GIT_ROOT}/${GIT_MAN_REL_DIR}"
+  GIT_MAN_TARBALL="${GIT_ROOT}/${GIT_MAN_REL_DIR}.tar.gz"
+
+  if ! [ -d "${GIT_MAN_TARBALL}" ]; then 
+    if ! curl -L "${ZOPEN_TARBALL_MAN_URL}" -o "${GIT_MAN_TARBALL}" ; then
+      printSoftError "Unable to download ${GIT_MAN_TARBALL} from ${ZOPEN_TARBALL_MAN_URL}"
+      return 4
+    fi
+  fi
+  if ! rm -rf  "${GIT_MAN_DIR}"  || ! mkdir "${GIT_MAN_DIR}" || ! tar -C "${GIT_MAN_DIR}" -axf "${GIT_MAN_TARBALL}" ; then
+    printSoftError "Unable to untar and create directory ${GIT_MAN_DIR}" 
+    return 4
+  fi
+
+  cp -rf "${GIT_MAN_DIR}/git-lfs-${GITLFS_VERSION}/man" "$ZOPEN_INSTALL_DIR/man"
+}
+
+zopen_check_results()
+{
+  chk="$1/$2_check.log"
+  successes=$(egrep "^ok [0-9]" "${chk}" | wc -l | xargs)
+
+  failuretests=$(egrep "^not ok [0-9]" "${chk}")
+  failures=$(echo "${failuretests}" | wc -l | xargs)
+  totalTests=$((failures+successes))
+
+  echo "${failuretests}" >"$1/$2_check_failures.log"
+
+cat <<ZZ
+actualFailures:$failures
+totalTests:$totalTests
+expectedFailures:3
+ZZ
+}
+
 zopen_get_version()
 {
-  echo "1.0.0"
+  echo "${GITLFS_VERSION}"
 }
